name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [ready_for_review]
    branches: ["main"]

permissions: 
  id-token: write
  contents: read

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest

    # services:
    #   postgres:
    #     image: bitnami/postgresql
    #     ports:
    #       - 5432:5432
    #     env:
    #       POSTGRESQL_USERNAME: ${{ secrets.DATABASE_USERNAME }}
    #       POSTGRESQL_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
    #       POSTGRESQL_DATABASE: ${{ secrets.DATABASE_NAME }}

    strategy:
      matrix:
        node: [22.16.0]

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install Pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run unit test
        run: pnpm test

      # - name: Wait for DB ready
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y postgresql-client
      #     until pg_isready -h localhost -p 5432 -U ${{ secrets.DATABASE_USERNAME }}; do
      #       echo "Waiting for database to be ready..."
      #       sleep 2
      #     done

      # - name: Test DB connection
      #   run: |
      #     sudo apt-get install -y postgresql-client
      #     echo "Testing connection with simple SQL..."
      #     PGPASSWORD=${{ secrets.DATABASE_PASSWORD }} \
      #       psql -h localhost -U ${{ secrets.DATABASE_USERNAME }} -d ${{ secrets.DATABASE_NAME }} \
      #       -c "SELECT datname, datcollate, datctype FROM pg_database;"

      # - name: Run Prisma Generate
      #   run: pnpm prisma generate

      # - name: Run E2E tests
      #   run: pnpm test:e2e
      #   env:
      #     DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      #     DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      #     DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      #     DATABASE_URL: ${{ secrets.DATABASE_URL }}
      #     JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
      #     JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY }}

      - name: Generate Tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Configure AWS  credentials
        if: false
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ''
          aws-region: aws-east-2

      - name: Login to AWS ECR
        id: login-ecr
        if: false
        uses: aws-actions/amazon-ecr-login@v2

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ vars.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Push image
      #   uses: docker/build-push-action@v6
      #   with:
      #     push: true
      #     tags: ${{ vars.DOCKERHUB_USERNAME }}/05-nest-clean:${{ steps.generate_tag.outputs.sha }}, ${{ vars.DOCKERHUB_USERNAME }}/05-nest-clean:latest
