name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [ready_for_review]
    branches: ["main"]

permissions: 
  id-token: write
  contents: read

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [22.16.0]

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install Pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run unit test
        run: pnpm test

      - name: Generate Tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Configure AWS  credentials
        if: false
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ID }}
          aws-region: aws-east-2

      - name: Login to AWS ECR
        id: login_ecr
        if: false
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build docker image
        if: false
        env: 
          REGISTRY: ${{ steps.login_ecr.outputs.registry }}
          TAG: ${{ steps.generate_tag.outputs.sha }}
        run: |
          docker build -t $REGISTRY/05-nest-clean:$TAG .
          docker push $REGISTRY/05-nest-clean:$TAG